### ISSUE TITLE
How to fix the hole after using meshcut

### ISSUE THREAD

**Issue by LiuKaoji** [Harold2017/m_math#1]
Thanks your great work.  The mesh has a hole after using the function. How to  make  a mesh is oriented, manifold, and connected to get HalfEdgeMesh to fill the mesh hole……^_^

bool MeshCut(open3d::geometry::TriangleMesh const& mesh,
             Eigen::Vector3d const& plane_center,
             Eigen::Vector3d const& plane_normal,
             open3d::geometry::TriangleMesh& l_mesh,
             open3d::geometry::TriangleMesh& r_mesh,
             std::vector<size_t>& r_tmp_mesh_intersected_pt_indices)

**Comment by Harold2017** [comment]
Actually for my own usage, i did require this hole exist. But if you want to fill this hole, you need to generate a plane mesh by those intersected points, which can be easily done by using earcut method. Please refer to [this example](https://github.com/Harold2017/m_math/blob/master/examples/mesh_cut.cpp).

This simple function will help you:
```c++
std::vector<Eigen::Vector3i> PolygonTriangulation(std::vector<Eigen::Vector2d> const& pts) {
    auto indices = mapbox::earcut<size_t>(std::vector<std::vector<Eigen::Vector2d>>{ pts });
    std::vector<Eigen::Vector3i> triangles;
    triangles.reserve(indices.size() / 3);
    for (auto i = 0; i < indices.size(); i += 3)
        triangles.emplace_back(indices[i], indices[i + 1], indices[i + 2]);
    return triangles;
}
```

**Comment by LiuKaoji** [comment]
Thanks for your good idea.I‘ll try it later.
